###
GET http://localhost:4000/api/employees

###

POST http://localhost:4000/api/employees
Content-Type: application/json

{
    "name": "Iliana Carolinaaaa",
    "office":"Madrid",
    "position":"Sr. Architect",
    "salary": 3000
}

###
GET http://localhost:4000/api/employees/

###

PUT http://localhost:4000/localhost:4000/api/employees/
Content-Type: application/json

{
    "salary": 30000
}